FROM node:alpine AS build

WORKDIR /frontend

COPY frontend/package.json /frontend/

RUN npm install
RUN npm install web-vitals
RUN npm install bootstrap

COPY frontend/ /frontend

RUN npm run build

FROM alpine:latest

RUN apk add --no-cache nodejs npm

WORKDIR /frontend

COPY --from=build /frontend/build .

RUN npm install -g http-server

EXPOSE 3000

CMD ["http-server", "-p", "3000"]
